version: "3.8"

services:
  linux:
    container_name: linux
    build: .
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./:/home/src
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined